#!/usr/bin/env bash

set -e
set -u

## Lockfile command
lock_file_or_dir="/var/lock/pull-obsidian-sync"
cmd_locking="mkdir ${lock_file_or_dir}"
cmd_check_lock="test -d ${lock_file_or_dir}"
cmd_unlocking="rm -rf ${lock_file_or_dir}"

## Manage Lockfile
function is_running()
{
    local cmd_check_lock=${1}
    
    ${cmd_check_lock} || {
        return 1
    }
    
    return 0
}

function create_lock()
{
    local cmd_locking=${1}
    
    ${cmd_locking} || {
        printf "Cannot create lock\\n"
        exit 2
    }
}

function remove_lock()
{
    local cmd_unlocking="${1}"
    
    ${cmd_unlocking} || {
        printf "Cannot unlock\\n"
        exit 3
    }
}

trap 'remove_lock "${cmd_unlocking}"' SIGINT SIGTERM

if is_running "${cmd_check_lock}"; then
    printf "Cannot acquire lock -> exiting\\n"
    exit 1
fi

create_lock "${cmd_locking}"


## Important variables
PATH_TO_APOCRYPTA_GLOBAL="$HOME/Documents/apocrypta-global"
PATH_TO_KEY="$HOME/Documents/apocrypta-global/apocrypta-key"

## Script body
### 0. Go to apocrypta remote repository
cd "$PATH_TO_APOCRYPTA_GLOBAL/apocrypta" || {
    remove_lock "${cmd_unlocking}"
    printf "Cannot cd to $PATH_TO_APOCRYPTA_GLOBAL/apocrypta -> exiting"
    exit 1
}

### 1. Pull changes from remote
git fetch || {
    remove_lock "${cmd_unlocking}"
    printf "Cannot \"git fetch\" -> exiting"
    exit 2
}

git pull || {
    remove_lock "${cmd_unlocking}"
    printf "Cannot \"git pull\" -> exiting"
    exit 2
}

### 2. Decrypt archive
age -d -i $PATH_TO_KEY -o "../apocrypta-vault.dec.tar" "apocrypta-vault.tar.enc" || {
    remove_lock "${cmd_unlocking}"
    printf "Cannot decrypt archive with $PATH_TO_KEY -> exiting"
    exit 3
}

### 3. Extract archive
cd "$PATH_TO_APOCRYPTA_GLOBAL" || {
    remove_lock "${cmd_unlocking}"
    printf "Cannot cd to $PATH_TO_APOCRYPTA_GLOBAL -> exiting"
    exit 4
}

tar -xf "apocrypta-vault.dec.tar" -C "apocrypta-vault" || {
    remove_lock "${cmd_unlocking}"
    printf "Cannot extract archive -> exiting"
    exit 5
}

## end body

remove_lock "${cmd_unlocking}"